[package]
org = "healthcare"
name = "health.fhir.r4.uscore501.patient"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]
template = true
