[package]
org = "ballerinax"
name = "cds_service"
version = "1.0.0"
distribution = "2201.12.10"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CRD", "Da Vinci", "CDS", "Coverage Requirements Discovery"]
template = true
