[package]
org = "healthcare"
name = "health.fhir.r4.uscore700.careteam"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CareTeam", "r4", "health.fhir.r4.uscore700"]
template = true
