[package]
org = "healthcare"
name = "health.fhir.r4.carinbb200.relatedperson"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "RelatedPerson", "r4", "health.fhir.r4.carinbb200"]
template = true
