[package]
org = "healthcare"
name = "health.fhir.r4.davincidrug.insuranceplan"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "InsurancePlan", "r4", "health.fhir.r4.davincidrug"]
template = true
