## These are sample configurations for the FHIR service.
## Update the values as per your environment setup.
exportServiceUrl = "http://localhost:8090/bulk/export"

## Initial sample data is dynamically retrieved from this GitHub repository.
sampleDataGithubUrl = "http://localhost:9091/data"

baseUrl = "http://localhost:9090/fhir/r4"

[ballerina.http]
defaultListenerPort = 8080

## Following configurations are used to build the capability statement and smart configuration.
[configs]
discoveryEndpoint = "https://api.asgardeo.io/t/wso2healthcare/oauth2/token/.well-known/openid-configuration"
[configs.smartConfiguration]
issuer = "<issuer>"
jwksUri = "<jwksUri>"
authorizationEndpoint = "<authorizationEndpoint>"
tokenEndpoint = "<tokenEndpoint>"
codeChallengeMethodsSupported = ["S256"]
grantTypesSupported = ["authorization_code"]
capabilities = ["launch-ehr"]

[configFHIRServer]
status = "active"
kind = "instance"
implementationDescription = "FHIR server"
fhirVersion = "4.0.1"
format = ["json"]

[configRest]
mode = "server"
