[package]
org = "healthcare"
name = "health.fhir.r4.uscore311.careplan"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CarePlan", "r4", "health.fhir.r4.uscore311"]
template = true
