[package]
org = "wso2"
name = "medicationrequest.api"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "MedicationRequest", "r4", "health.fhir.r4.uscore700"]
template = true
